version: '2'

services:
  app:
    image: 'ledgercoin-app:latest'
    container_name: ledgercoin-app
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://testcomposeuser:Test123@mongodb:27017/ledgercoin?retryWrites=true&w=majority
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:6.0'
    container_name: mongo
    volumes:
      - ./mongoDBSetup.js:/docker-entrypoint-initdb.d/setup.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testcomposeuser
      - MONGO_INITDB_ROOT_PASSWORD=Test123
      - MONGO_INITDB_DATABASE=ledgercoin
    
